/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise AI System — REST API
 * Synchronous REST API for the Enterprise AI System. High-volume async flows use Kafka events (see asyncapi.yaml). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    SLOStatusResponse,
} from '../models/index';

/**
 * 
 */
export class GovernanceApi extends runtime.BaseAPI {

    /**
     * Creates request options for getSloStatus without sending the request
     */
    async getSloStatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/governance/slo-status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns every SLO defined in docs/sre/slo/slo.yaml with an honest observed block. Requires a bearer JWT (read access). target/target_ms/target_max and window are the real configured SLO definitions. observed.data_available is true only where a real in-process sample exists (api-gateway availability/error-rate, scoped as a process-lifetime sample); everywhere else it is false with a note — no observed number is ever fabricated (computing 30-day SLO compliance / burn-rate needs a metrics-query layer the service lacks). SPEC-API-004, CLAUDE.md §3.6.
     * SLO targets and honest observed status
     */
    async getSloStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SLOStatusResponse>> {
        const requestOptions = await this.getSloStatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns every SLO defined in docs/sre/slo/slo.yaml with an honest observed block. Requires a bearer JWT (read access). target/target_ms/target_max and window are the real configured SLO definitions. observed.data_available is true only where a real in-process sample exists (api-gateway availability/error-rate, scoped as a process-lifetime sample); everywhere else it is false with a note — no observed number is ever fabricated (computing 30-day SLO compliance / burn-rate needs a metrics-query layer the service lacks). SPEC-API-004, CLAUDE.md §3.6.
     * SLO targets and honest observed status
     */
    async getSloStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SLOStatusResponse> {
        const response = await this.getSloStatusRaw(initOverrides);
        return await response.value();
    }

}
