/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise AI System — REST API
 * Synchronous REST API for the Enterprise AI System. High-volume async flows use Kafka events (see asyncapi.yaml). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    RunTraceResponse,
} from '../models/index';

export interface GetRunTraceRequest {
    requestId: string;
}

/**
 * 
 */
export class RunsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getRunTrace without sending the request
     */
    async getRunTraceRequestOpts(requestParameters: GetRunTraceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling getRunTrace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/runs/{request_id}`;
        urlPath = urlPath.replace('{request_id}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the execution trace for a single submitted request: its state plus a timeline of audit events that can be REALLY associated with it. Requires a bearer JWT (read access). timeline_association names the strategy that built the timeline — the audit store is not indexed by the domain request_id, so an exact trace is only available when an event\'s metadata.request_id matches; otherwise timeline is empty and timeline_association is \"none\" (SPEC-API-004 §9.1, CLAUDE.md §3.6 — no fabricated linkage).
     * Get a request\'s execution trace
     */
    async getRunTraceRaw(requestParameters: GetRunTraceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RunTraceResponse>> {
        const requestOptions = await this.getRunTraceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the execution trace for a single submitted request: its state plus a timeline of audit events that can be REALLY associated with it. Requires a bearer JWT (read access). timeline_association names the strategy that built the timeline — the audit store is not indexed by the domain request_id, so an exact trace is only available when an event\'s metadata.request_id matches; otherwise timeline is empty and timeline_association is \"none\" (SPEC-API-004 §9.1, CLAUDE.md §3.6 — no fabricated linkage).
     * Get a request\'s execution trace
     */
    async getRunTrace(requestParameters: GetRunTraceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RunTraceResponse> {
        const response = await this.getRunTraceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
