#!/usr/bin/env bash
# run_restore_drill.sh — orchestrate a restore drill across all stateful stores.
#
# Runs the per-store restore scripts (Aurora PITR, Redis, Kafka) and writes a
# dated evidence file into docs/resilience/restore-drills/YYYY-MM-DD.md following
# the convention in docs/resilience/backup-restore-policy.md.
#
# DRY-RUN BY DEFAULT: with no flags every store restore runs in --dry-run, so the
# drill performs NO AWS mutations and is safe to run in CI. Pass --execute to run
# the real restore (intended for a human-approved drill / the deferred scheduled
# workflow — see ADR-0082 §Follow-up).
#
# Config: see the per-store scripts for store-specific environment variables.
#   DRILL_OWNER  recorded as the drill owner in the evidence file (default: $USER or "unknown")
#
# Spec: docs/resilience/backup-restore-policy.md · docs/resilience/dr-plan.md · ADR-0082
set -euo pipefail

SCRIPT_NAME="$(basename "$0")"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
EVIDENCE_DIR="${REPO_ROOT}/docs/resilience/restore-drills"

usage() {
  cat <<EOF
Usage: ${SCRIPT_NAME} [--dry-run | --execute] [-h|--help]

Orchestrate a restore drill across Aurora, Redis, and Kafka, then write a dated
evidence file into docs/resilience/restore-drills/.

Options:
  --dry-run   Run every store restore in dry-run; write evidence (default).
  --execute   Run real restores against throwaway targets (requires AWS creds).
  -h, --help  Show this help and exit.

Environment:
  DRILL_OWNER  owner recorded in the evidence file (default: \$USER or "unknown")
  (plus the per-store variables documented in each restore_*.sh script)
EOF
}

MODE="dry-run"
while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run) MODE="dry-run" ;;
    --execute) MODE="execute" ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

DRILL_DATE="$(date -u +%Y-%m-%d)"
DRILL_TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
DRILL_OWNER="${DRILL_OWNER:-${USER:-unknown}}"
EVIDENCE_FILE="${EVIDENCE_DIR}/${DRILL_DATE}.md"

echo "== Restore drill (${MODE}) =="
echo "  date:     ${DRILL_DATE}"
echo "  owner:    ${DRILL_OWNER}"
echo "  evidence: ${EVIDENCE_FILE}"
echo

STORES=(
  "Aurora PostgreSQL (PITR)|restore_aurora_pitr.sh"
  "Redis (ElastiCache snapshot)|restore_redis_snapshot.sh"
  "Kafka (MSK snapshot)|restore_kafka_snapshot.sh"
)

declare -a RESULTS
OVERALL="PASS"

for entry in "${STORES[@]}"; do
  label="${entry%%|*}"
  script="${entry##*|}"
  echo "---- ${label} (${script}) ----"
  if bash "${SCRIPT_DIR}/${script}" "--${MODE}"; then
    RESULTS+=("${label}|PASS")
  else
    RESULTS+=("${label}|FAIL")
    OVERALL="FAIL"
  fi
  echo
done

mkdir -p "${EVIDENCE_DIR}"

{
  echo "# Restore drill — ${DRILL_DATE}"
  echo
  echo "- **Date (UTC):** ${DRILL_TS}"
  echo "- **Owner:** ${DRILL_OWNER}"
  echo "- **Mode:** ${MODE}"
  echo "- **Overall result:** ${OVERALL}"
  echo "- **Trigger:** $([ "${MODE}" = "execute" ] && echo "approved drill / scheduled workflow" || echo "dry-run (no AWS mutations)")"
  echo
  echo "## What was restored"
  echo
  echo "| Store | Script | Plan/restore result |"
  echo "| ----- | ------ | ------------------- |"
  for entry in "${STORES[@]}"; do
    label="${entry%%|*}"
    script="${entry##*|}"
    res="PASS"
    for r in "${RESULTS[@]}"; do
      [ "${r%%|*}" = "${label}" ] && res="${r##*|}"
    done
    echo "| ${label} | \`scripts/restore/${script}\` | ${res} |"
  done
  echo
  echo "## RTO achieved"
  echo
  echo "- _Dry-run does not measure RTO. For an --execute drill, record wall-clock time"
  echo "  from restore start to integrity-check pass, and compare against the per-service"
  echo "  RTO in docs/resilience/dr-plan.md / docs/runbooks/disaster-recovery.md (RB-002)._"
  echo "- RTO achieved: TODO"
  echo
  echo "## Integrity result"
  echo
  echo "- _Run integrity checks against the restored throwaway target (row counts, key"
  echo "  sampling, topic offsets). Dry-run records plan validity only._"
  echo "- Integrity: $([ "${MODE}" = "execute" ] && echo "TODO" || echo "n/a (dry-run)")"
  echo
  echo "## Issues / follow-ups"
  echo
  echo "- _None recorded automatically. Add any anomalies, then file issues as needed._"
  echo
  echo "---"
  echo
  echo "_Generated by \`scripts/restore/run_restore_drill.sh\` (ADR-0082)._"
} >"${EVIDENCE_FILE}"

echo "== Evidence written: ${EVIDENCE_FILE} (overall: ${OVERALL}) =="

[ "${OVERALL}" = "PASS" ]
